### ISSUE TITLE
Jodel assisted error report V2.2

### ISSUE THREAD

**Issue by jdirocco** [MDEGroup/jjodel#5]
<img width="636" alt="image" src="https://github.com/user-attachments/assets/851e0c27-938a-4d9f-abdf-3bef26d37c8a">

This mail is auto-generated, it might contain data of your views or model.
If your project have sensitive personal information please do a manual report instead.Cannot read properties of undefined (reading 'Pointer1725356041105_USER_jdirocco')

_stack:
TypeError: Cannot read properties o...USER_jdirocco')
    at VertexComponent.render (http...8.js:174465:82)
    at VertexComponent.render (http....js:174923:402)
    at qi (http://193.204.135.225/j...8.js:119695:76)
    at pi (http://193.204.135.225/j...8.js:119687:10)
    at ck (http://193.204.135.225/j...8.js:121739:86)
    at bk (http://193.204.135.225/j...8.js:121232:11)
    at ak (http://193.204.135.225/j...28.js:121223:5)
    at Tj (http://193.204.135.225/j...28.js:121207:7)
    at Lj (http://193.204.135.225/j...8.js:120978:28)
    at http://193.204.135.225/jjode...28.js:118267:17

_component_stack:

    at VertexComponent (http://193....:719)
    at ConnectFunction (http://193....5:75)
    at DefaultNodeComponent (http:/...:785)
    at ConnectFunction (http://193....5:75)
    at DefaultNode
    at div
    at div
    at div
    at MetamodelTabComponent (http:...3:55)
...

**Comment by GiordanoT** [comment]
Fixed: User (collaborator) creation in collaborative environment
